services:
    consumer-app.test:
        build:
            context: './'
            dockerfile: .docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8081}:80'
            - '${GRPC_PORT:-50051}:50051'
            - '${VITE_PORT:-15171}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - sail-shared   # 👈 Add this line
        depends_on: {  }
networks:
    sail:
        driver: bridge
    sail-shared:
        external: true    # 👈 Mark as external
